server:
  port: 9001
spring:
  application:
    name: cloud-order-service #服务名称

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddemo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: qq13579..

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
logging:
  config: classpath:log4j2.xml
  level:
    com:
     cafebabe:
      clouddemo:
       eureka:
        consumer:
         dao: debug

eureka:
  client:
    register-with-eureka: true #向server注册
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka